#!/usr/bin/env bash
# Run libp2p/unified-testing transport matrix against the local zig-libp2p tree.
# Requires bash 4+, docker, yq, and git. On macOS: brew install bash yq

set -euo pipefail

if [ "${BASH_VERSINFO[0]:-0}" -lt 4 ]; then
  echo "error: bash 4+ required (macOS: brew install bash, then re-run with that bash)" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

UNIFIED_TESTING_REPO="${UNIFIED_TESTING_REPO:-libp2p/unified-testing}"
UNIFIED_TESTING_REF="${UNIFIED_TESTING_REF:-master}"
CACHE_DIR="${CACHE_DIR:-${REPO_ROOT}/.cache/unified-testing}"
UNIFIED_TESTING_DIR="${UNIFIED_TESTING_DIR:-${CACHE_DIR}/repo}"
IMAGES_YAML="${IMAGES_YAML:-${SCRIPT_DIR}/images.local.yaml}"
WORKERS="${WORKERS:-2}"

for cmd in docker yq git; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "error: ${cmd} is required" >&2
    exit 1
  fi
done

mkdir -p "${CACHE_DIR}"

if [ ! -d "${UNIFIED_TESTING_DIR}/.git" ]; then
  echo "→ Cloning ${UNIFIED_TESTING_REPO} (${UNIFIED_TESTING_REF})"
  git clone --depth 1 --branch "${UNIFIED_TESTING_REF}" \
    "https://github.com/${UNIFIED_TESTING_REPO}.git" "${UNIFIED_TESTING_DIR}"
else
  echo "→ Updating ${UNIFIED_TESTING_DIR}"
  git -C "${UNIFIED_TESTING_DIR}" fetch --depth 1 origin "${UNIFIED_TESTING_REF}"
  git -C "${UNIFIED_TESTING_DIR}" checkout -q FETCH_HEAD
fi

cat >"${IMAGES_YAML}" <<EOF
# Generated by interop/run_unified_testing.sh — local zig-libp2p + rust-v0.56 cross-test.
test-aliases:
  - alias: zig
    value: zig-libp2p-local
  - alias: rust
    value: rust-v0.56

implementations:
  - id: zig-libp2p-local
    source:
      type: local
      path: ${REPO_ROOT}
      dockerfile: interop/Dockerfile
    transports: [tcp]
    secureChannels: [tls]
    muxers: [yamux]

  - id: rust-v0.56
    source:
      type: github
      repo: libp2p/rust-libp2p
      commit: 70082df7e6181722630eabc5de5373733aac9a21
      dockerfile: interop-tests/Dockerfile.native
      patchPath: images/rust/v0.56
      patchFile: transport-fix.patch
    transports: [tcp]
    secureChannels: [tls]
    muxers: [yamux]
EOF

echo "→ Running unified-testing transport matrix"
cd "${UNIFIED_TESTING_DIR}/transport"
export IMAGES_YAML
export CACHE_DIR="${CACHE_DIR}/transport-cache"
export TEST_ROOT="${UNIFIED_TESTING_DIR}/transport"

./run.sh \
  --yes \
  --workers "${WORKERS}" \
  --force-image-rebuild \
  --impl-select "zig-libp2p-local|rust-v0.56" \
  --transport-select "tcp" \
  --secure-select "tls" \
  --muxer-select "yamux" \
  "$@"

echo "✓ unified-testing transport matrix passed"
